services:
  gui-webserver:
    container_name: gui-webserver
    build:
      dockerfile: './GUI - Dockerfile'
    image: gui-webserver
    environment:
      - WEB_PORT=80
    ports:
      # Use the same port as WEB_PORT as the internal container port (right number)
      - "8000:80"

  ai-webserver:
    container_name: ai-webserver
    build:
      dockerfile: './AI - Dockerfile'
    image: ai-webserver
    environment:
      - AI_PORT=80
    ports:
      # Use the same port as AI_PORT as the internal container port (right number)
      - "8001:80"